baseURL = "https://TU-USUARIO.github.io/"
title = "Mi Tienda de Ropa"
theme = "hugo-theme-stack"

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[taxonomies]
  category = "categories"
  tag = "tags"

[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack"

[params]
  mainSections = ["productos"]
  showAllPagesInArchive = true
